#!/usr/bin/env node
/**
 * Generate env.js from environment variables.
 * Usage:
 *   GOOGLE_CLIENT_ID=your-id node scripts/generate-env.js
 * Or create a .env file (optional): GOOGLE_CLIENT_ID=your-id
 *   node scripts/generate-env.js
 *
 * Output is written to env.js in the project root.
 */

try { require('dotenv').config(); } catch (e) {}

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const clientId = process.env.GOOGLE_CLIENT_ID || '';

const content =
  '// Generated by scripts/generate-env.js – do not commit if it contains secrets\n' +
  'window.GOOGLE_CLIENT_ID = ' + JSON.stringify(clientId) + ';\n';

fs.writeFileSync(path.join(root, 'env.js'), content, 'utf8');
console.log('Wrote env.js (GOOGLE_CLIENT_ID from env)');
